 #lang racket
(provide (all-defined-out))

;; THIS FILE CONTAINS ALL THE USER-DEFINED SETTINGS. THIS CAN BE FREELY CHANGED EXCEPT LAST FOUR.
;; NUMBER OF COLUMNS = M AND NUMBER OF ROWS = N.
;; SCALE = 1 GIVES A WINDOW OF 1400x700 PIXELS.
;; SCALE = x GIVES A WINDOW OF (* x 1400) x (* x 700) PIXELS AND ALL THE ELEMENTS ARE ALSO SCALED BY FACTOR OF X.
;; BACK COLOR IS BACKGROUND COLOR
;; GRID COLOR IS COLOR OF LINES FORMING THE GRID
;; OVERLAY-COLOR SHOULD BE A COLOR CONTRASTING TO BACK COLOR FOR PROPER VISIBILITY OF BUTTONS.
;; EXECUTION-TIME IS THE AI TO COMPUTE THE NEXT MOVE. LARGER THE TIME, BETTER THE MOVE.
;; M SHOULD BE LESS THAN 13, N SHOULD BE LESS THAN 8.
(define M 12)
(define N 7)
(define SCALE 1)
(define BACK-COLOR 'black)
(define OVERLAY-COLOR 'aquamarine)
(define GRID-COLOR 'LightSkyBlue)
(define EXECUTION-TIME 10000)

;; THE COLORS BELOW MAY ONLY BE 'red, 'blue, 'green, 'yellow.
;; THE PROGRAM DOES NOT SHOW ERROR. THE REQUIRED ORBS WILL NOT BE SEEN ON GRID.
;; IDEALLY ALL COLORS SHOULD BE DISTINCT. HOWEVER THE PROGRAM RUNS CORRECTLY ANYWAYS.
(define PLAYER1-COLOR 'blue)
(define PLAYER2-COLOR 'red)
(define PLAYER3-COLOR 'green)
(define PLAYER4-COLOR 'yellow)

